name: ukk_2025
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Tambahkan dependensi untuk Supabase
  supabase_flutter: ^0.2.10  # Pastikan untuk menggunakan versi terbaru
  flutter_dotenv: ^5.0.2  
  google_fonts: ^2.1.0 # Untuk menggunakan file .env (opsional, untuk menyimpan API keys secara aman)
  shared_preferences: ^2.0.11
  image_picker: ^0.8.5+3
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Tambahkan path ke aset gambar
  assets:
    - assets/images/logohomepage.png
    - assets/images/avatar.png
    - assets/images/homepagebg.jpg
    - assets/images/admin.png
    